#+title:      Hello Worg, the Org-Mode Community!
#+author:     Worg people
#+email:      mdl AT imapmail DOT org
#+startup:    align fold nodlcheck hidestars oddeven intestate
#+seq_todo:   TODO(t) INPROGRESS(i) WAITING(w@) | DONE(d) CANCELED(c@)
#+tags:       Write(w) Update(u) Fix(f) Check(c)
#+language:   en
#+category:   worg
#+options:    H:3 num:nil toc:t \n:nil ::t |:t ^:t -:t f:t *:t tex:t d:(HIDE) tags:not-in-toc

# For this dynamic block to work, you need to add code/elisp/worg.el in
# your load-path.

# Let say that you like Emacs and that you like using org-mode for editing
# structured files in Emacs.  Then you might want to /share/ some =.org=
# files and ask people to edit them with you.  This is what *Worg* is about:
# collaboratively editing Org files to build a knowledge database about
# =.org= itself (and planning-related stuff.)

# We put true links to the server, as sitemap.org and theindex.org are
# generated on the server during the publication

Sitemap and index

* Introduction to Org-Mode and Worg

Org-mode is a powerful system for organizing your complex life with
simple plain-text files.  It seamlessly integrates all your notes,
mindmaps, TODO lists, calendar, day planner, and project schedules
into a single system that can be easily searched (e.g. by grep),
encrypted (e.g. by GnuPG), backed up and synced (e.g.  by Dropbox),
imported/exported, and accessed on the go (e.g. on an iPhone or
Android smartphone).  It can even be used for authoring web pages and
documents.

Check out some screenshots of Org-mode in action.  See what people
have to say about Org-mode, and read a few user stories!

Org-mode is distributed as part of the popular Emacs text editor and
runs wherever Emacs runs, including on GNU-Linux, Windows, and Mac.
Written by Carsten Dominik, it is currently maintained by Bastien
Guerry and used by many helpful people who, like you, are desperate to
get and stay organized.  The way Org-mode maintenance is done is
described here.

The page you're reading is part of =Worg=, a section of the Org-mode web
site that is written by a volunteer community of Org-mode fans.  It
includes tutorials, ideas, code snippets, etc., shared to make your
introduction and customization of Org-mode as easy as possible.  Worg
is maintained by Matthew Lundin, a group of Worg contributors, and
maybe you.

* Org-Mode Resources
  :PROPERTIES:
  :ID:       A6F83C16-B1B9-405A-B996-8D2CA1274DEB
  :END:

** Learn Org-Mode

#+index: Tutorials
#+index: Glossary

- Org-mode Tutorials : Your best starting points for a relaxed overview
- Org-mode Manual : Extensive and complete documentation
- Org-mode Guide : Not extensive, but complete documentation (also in spanish and french)
- Org-mode Glossary : An explanation of org-mode terminology
- Org-mode configuration : Beginner's customization guide, examples, survey, and a list of hooks
- Org-mode reference card : Check the HTML, pdf and ASCII versions and the French translation (tex - pdf)
- Org-mode Main Page : The official page for Org-mode with pointers to everything else

** Get Help with Org-Mode

- Org-mode FAQ : Check here before writing to the mailing list
- Org-mode Mailing List : For unanswered questions, suggestions, and discussion
- Org-mode IRC Channel : For live Q&A, go to =#org-mode= on Freenode
- Check latest posts on reddit.com and stackoverflow.com
- Browse Org-mode discussions on reddit.com
- Browse Org-mode questions on stackoverflow.com

** Use Org-Mode Effectively

- Use Org-mode as a task management system (GTD and Pomodoro)
- Author Blogs and Wikis with Org-mode (see Personal Web Sites)
- Synchronize org-mode files with git-sync, a VCS of your choice, or Unison
- Integrate Org-mode with Mac OS X

** Dive Deeper into Org-Mode

- Org-mode Hacks : Copy code snippets from other users
- Org-mode for developers : Reference documentation for developers
- Blog posts : Read a variety of articles from introductions to specific customizations
- Babel : Literate programming with active source code blocks
- Org-mode parsing libraries : Parse and analyze =.org= files
- Org-mode conversion tools  : Import into and export out of Org-mode
- Org-mode dependencies : Dependencies on external packages for advanced functionality
- Org-papers : Whitepapers and books about Org-mode
- Keep your Org-files tidy : Suggestions for attentive users

** Check Out Third-Party Contributions

- Contributed packages, including extensive documentation
- Additions under development

* Help us sustain our efforts

Org-mode is maintained and developed by volunteers on their free time.

You can help us dedicate more of our energy by making a donation or
contributing directly.

** Worg maintenance
:PROPERTIES:
:CUSTOM_ID: worg-maintaince
:END:

- About the Worg project
- How Worg is set up on the server
- About Worg maintainer and gardeners
- The Worg TODO file
- An introduction to git for Worgers
- Conventions and tools for editing Worg
- How to create your own SSH key?
- Recent changes to Worg
- Org-mode source documents of all Worg pages

** Join the Community

Check out the list of Worgers and their User Pages and a few profiles
of the Org-mode Community (with photos ☺).  You can also meet other
users in the flesh at OrgCamps.

** Git'r done!

If you like losing your time by reading stuff on how to get organized,
go and check the Git'r done! page.